### ISSUE TITLE
Many Days Graph TODO

### ISSUE THREAD

**Issue by micz** [micz/ThunderStats#235]
Many Days Graph

- [x] Add value numbers
- [x] Improve labels
- [x] Change bar colors
- [x] Set Y max value: round to /5 /0
- [x] Ticks only integers

From version 1.4.5:
![164702](https://github.com/micz/ThunderStats/assets/61795/eefed4e8-bfdb-4c06-ab2b-b46c7154dbcb)
